### ISSUE TITLE
Sidekiq dependency

### ISSUE THREAD

**Issue by seifsallam** [dlibanori/sidekiq-delay#1]
Can you update the gem dependency of sidekiq to (~> 2.14.1)? I really would love to use your gem.

**Comment by dlibanori** [comment]
Done. If you get any bug, please, open an issue.

**Comment by seifsallam** [comment]
Sorry i haven't mentioned it. I'm using rails 4, and now it's asking for activesupport (~> 3.2.13), while i'm using activesupport 4.0. Is it possible that you can update that too?

**Comment by dlibanori** [comment]
Go ahead.

**Comment by seifsallam** [comment]
Awesome, Thanks alot man :+1:
