### ISSUE TITLE
Sidekiq version

### ISSUE THREAD

**Issue by cblavier** [dlibanori/sidekiq-delay#3]
Hey, 

I tested your gem with sidekiq >= 3.0.0 and it seems to be working properly.
Could you please update your gemspec accordingly?

Thanks

**Comment by dlibanori** [comment]
Sure, I am going to upgrade it this week.

**Comment by cblavier** [comment]
Thanks!

**Comment by cblavier** [comment]
Any update on this issue?

**Comment by dlibanori** [comment]
Done.
